/* automatically generated by rust-bindgen 0.70.1 */
#![allow(warnings)]

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 40;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const RETURN_ERROR: i32 = -1;
pub const RETURN_OK: u32 = 0;
pub const MAX_WRAP: u32 = 280;
pub const MAX_LPOS: u32 = 730994;
pub const MAX_IO_NUM: u32 = 10000;
pub const MIN_IO_NUM: u32 = 10;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub const HEAD_STATUS_HEAD_STATIC: HEAD_STATUS = 0;
pub const HEAD_STATUS_HEAD_RW: HEAD_STATUS = 1;
pub const HEAD_STATUS_HEAD_STATUS_BUTT: HEAD_STATUS = 2;
pub type HEAD_STATUS = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HeadInfo {
    pub wrap: u32,
    pub lpos: u32,
    pub status: HEAD_STATUS,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IOUint {
    pub id: u32,
    pub wrap: u32,
    pub startLpos: u32,
    pub endLpos: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IOVector {
    pub len: u32,
    pub ioArray: *mut IOUint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[no_mangle]
pub struct InputParam {
    pub headInfo: HeadInfo,
    pub ioVec: IOVector,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[no_mangle]
pub struct OutputParam {
    pub len: u32,
    pub sequence: *mut u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KeyMetrics {
    pub ioCount: u32,
    pub algorithmRunningDuration: f64,
    pub memoryUse: ::std::os::raw::c_long,
    pub addressingDuration: u32,
    pub readDuration: u32,
    pub tapeBeltWear: u32,
    pub lposPassTime: [u16; 730994usize],
    pub tapeMotorWear: u32,
    pub errorIOCount: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TapeBeltSegWearInfo {
    pub segWear: [u16; 730994usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AccessTime {
    pub addressDuration: u32,
    pub readDuration: u32,
}
#[link(name = "seek_model")]
extern "C" {
    #[doc = " @brief 寻址时间计算\n @param  start            磁头起始位置和状态\n @param  target           目标位置和期望到达位置的状态\n @return uint32_t         返回时间，单位毫秒"]
    pub fn SeekTimeCalculate(start: *const HeadInfo, target: *const HeadInfo) -> u32;
    #[doc = " @brief  带体磨损计算\n @param  start            起始位置和状态\n @param  target           目标位置和状态\n @param  segWearInfo      带体的分段磨损信息，即记录磁头划过每个lpos的次数\n @return uint32_t         返回磁头所经过的LPOS数量，划过一个LPOS计数1次"]
    pub fn BeltWearTimes(
        start: *const HeadInfo,
        target: *const HeadInfo,
        segWearInfo: *mut TapeBeltSegWearInfo,
    ) -> u32;
    #[doc = " @brief  电机磨损计算\n @param  start            起始位置和状态\n @param  target           目标位置和状态\n @return uint32_t         返回电机的启停次数"]
    pub fn MotorWearTimes(start: *const HeadInfo, target: *const HeadInfo) -> u32;
    #[doc = " @brief 计算读IO数据的时间\n @param  startLpos        lpos范围\n @return uint32_t          毫秒"]
    pub fn ReadTimeCalculate(lposRange: u32) -> u32;
    #[doc = " @brief  计算批量IO的总访问时间，寻址时间+读IO数据时间\n @param  input            磁头和批量的IO信息\n @param  output           排序后的IO序列\n @param  accessTime       输出参数，访问时间结构体"]
    pub fn TotalAccessTime(
        input: *const InputParam,
        output: *const OutputParam,
        accessTime: *mut AccessTime,
    );
    #[doc = " @brief  统计磁带带体的磨损次数，即，划过一个LPOS计数1次\n @param  input            磁头和批量的IO信息\n @param  output           排序后的IO序列\n @param  segWearInfo      带体的分段磨损信息，即记录磁头划过每个lpos的次数\n @return uint32_t         带体磨损次数"]
    pub fn TotalTapeBeltWearTimes(
        input: *const InputParam,
        output: *const OutputParam,
        segWearInfo: *mut TapeBeltSegWearInfo,
    ) -> u32;
    #[doc = " @brief  统计电机磨损次数，即，启、停各计数1次，掉头计数2次，\n @param  input            磁头和批量的IO信息\n @param  output           排序后的IO序列\n @return uint32_t         电机磨损次数"]
    pub fn TotalMotorWearTimes(input: *const InputParam, output: *const OutputParam) -> u32;
}
