all: liballoc.rlib.o libcfg_if-0_1_10_H3.rlib.o libcompiler_builtins-0_1_45_H92.rlib.o \
	libcore.rlib.o libgetopts-0_2_21_H1.rlib.o libhashbrown-0_11_0_H328.rlib.o liblibc-0_2_95_H19.rlib.o \
	libmrustc_standard_library.rlib.o libpanic_abort.rlib.o libpanic_unwind.rlib.o \
	libproc_macro.rlib.o librustc_demangle-0_1_19_H3.rlib.o librustc_std_workspace_alloc-1_99_0.rlib.o \
	librustc_std_workspace_core-1_99_0.rlib.o librustc_std_workspace_std-1_99_0.rlib.o \
	libstd.rlib.o libstd_detect-0_1_5_Ha7.rlib.o libterm.rlib.o libtest.rlib.o \
	libunicode_width-0_1_8_Ha.rlib.o libunwind.rlib.o
